"""Pre-populate customers from the Aquacheck Laboratories customer list."""
from sqlalchemy.orm import Session
from app.models.customer import Customer

# (name, currency, is_active)
_CUSTOMERS = [
    ("Priscilla", "KES", True),
    ("Cana hospital", "KES", True),
    ("Lawrence", "KES", True),
    ("Josphine Njoroge", "KES", True),
    ("Millie Obunga", "KES", True),
    ("SILAFRICA", "KES", True),
    ("Palm Golding Properties", "KES", True),
    ("Mary Help of The Sick", "KES", True),
    ("RUBY MALL LTD", "KES", True),
    ("AG GROUP", "KES", True),
    ("HYDROMASTERS LTD", "KES", True),
    ("Chem-labs Limited", "KES", True),
    ("Aninver Development Partners SL", "KES", True),
    ("International Organisation for Migration", "KES", True),
    ("Christine Mwangi", "KES", True),
    ("KEMILY", "KES", True),
    ("Harrow Investment", "KES", True),
    ("Antony CLIENT", "KES", True),
    ("Antony", "KES", True),
    ("Morris Otieno", "KES", True),
    ("Moris Otieno", "KES", True),
    ("KARENE MELLOUL", "KES", True),
    ("LUSO FOOD $ BEVERAGES LTD", "KES", True),
    ("AMERICAN EMBASSY NAIROBI", "USD", True),
    ("Go Economic Empowerment Programme", "KES", True),
    ("Pure H2O Africa ltd", "KES", True),
    ("MX4-Kali Morgan", "KES", True),
    ("Charles Mburu", "KES", True),
    ("David Mwangi", "KES", True),
    ("Haijiang International company ltd", "KES", True),
    ("Benjamin Maina", "KES", True),
    ("scola nduku", "KES", True),
    ("JOB", "KES", True),
    ("Rombo Conservancy", "KES", True),
    ("Ruth Nyambura", "KES", True),
    ("Jane macharia", "KES", True),
    ("suka (kenya) new materials LTD", "KES", True),
    ("Pure water Africa", "KES", True),
    ("Ruth Nyambura Kibebo", "KES", True),
    ("George Odongo", "KES", True),
    ("Moja Expressway co.ltd", "KES", True),
    ("Tenitec Africa ltd", "KES", True),
    ("US embassy Nairobi", "KES", True),
    ("Apricot Property Solutions Ltd", "KES", True),
    ("Peba Growers", "KES", True),
    ("Kenya assemblies of God", "KES", True),
    ("All Africa Conference of Churches", "KES", True),
    ("Fogo Gaucho", "KES", True),
    ("Royal spring waves LTD", "KES", True),
    ("Robin samwel kiilu", "KES", True),
    ("Mr. Yoni", "KES", False),
    ("Ramco Printing Works- Mombasa RD", "KES", True),
    ("Modern Energy", "KES", True),
    ("Moedern Energy", "KES", True),
    ("Lekker enterprises", "KES", True),
    ("Benitec E.A ltd", "KES", True),
    ("Chiwakibe@yahoo.com", "KES", True),
    ("ALINA HARBOUR APARTMENTS", "KES", True),
    ("Richard Nderitu", "KES", True),
    ("PATH TO RUSSIA", "KES", True),
    ("Salim wazaran kenya co ltd", "KES", True),
    ("iKWETA", "KES", True),
    ("VIKAL MUKUND HIRAN", "KES", True),
    ("Robert", "KES", True),
    ("Savanna fibre Limited", "KES", True),
    ("Marina Bay Square Management Ltd", "KES", True),
    ("Legit water", "KES", True),
    ("Sanjowa Technical services", "KES", True),
    ("Eunice wangari", "KES", True),
    ("C& P shoe industries", "KES", True),
    ("CP solar", "KES", True),
    ("dmi kenya ltd", "KES", True),
    ("dmi", "KES", True),
    ("LA FONTANA INTERNATIONAL SCHOOL", "KES", True),
    ("ALKNAKKAS LTD", "KES", True),
    ("Heroes Pure drinks", "KES", True),
    ("Michael Mwendwa Ngui", "KES", True),
    ("KANHA Limited", "KES", True),
    ("Hydrosun Technologies Ltd", "KES", True),
    ("Kounkuey Design Initiative", "KES", True),
    ("Matuu Owino Firm Ltd", "KES", True),
    ("Compass Mafucturing", "KES", True),
    ("David wambiri", "KES", True),
    ("Desalytics", "KES", True),
    ("The Paper House Of Kenya Ltd", "KES", True),
    ("Inaya water Bottlers", "KES", True),
    ("Aquareal treaders", "KES", True),
    ("Serah Waichira", "KES", True),
    ("Hydromaster Ltd", "KES", True),
    ("Blue bay Hotel -zanzibar", "KES", True),
    ("Maryanne Mugami", "KES", True),
    ("Salim Ali", "KES", True),
    ("Itec water solutions", "KES", True),
    ("Proffex.K. ltd", "KES", True),
    ("Niaz Engineering Enterprises ltd", "KES", True),
    ("Oyo were", "KES", True),
    ("0704524852", "KES", True),
    ("Davita Management", "KES", True),
    ("Rachel Chakwera", "KES", True),
    ("Heri Homes Phase II", "KES", True),
    ("Spironet", "KES", True),
    ("Grace", "KES", True),
    ("Sohail Management Regency", "KES", True),
    ("Edvik Realty ltd", "KES", True),
    ("Waterlink Engineering services", "KES", True),
    ("Noor", "KES", True),
    ("Sawariya suppliers", "KES", True),
    ("Janitorial supplies ltd", "KES", True),
    ("Agnes Wairimu", "KES", True),
    ("Rostevi water technologies", "KES", True),
    ("Nile Instrumentation", "KES", True),
    ("EKA HOTEL ELDORET", "KES", True),
    ("LOCAL AUTHORITIES PENSION TRUST", "KES", True),
    ("Anton Vasyliev", "KES", True),
    ("KAGGS Investment limited", "KES", True),
    ("Simspark Solution Limited", "KES", True),
    ("Hillsview Water Co ltd", "KES", True),
    ("Acrembura Water services", "KES", True),
    ("GACHANI TRAINING INSTITUTE", "KES", True),
    ("Philip Mungai", "KES", True),
    ("Joseph Wafula", "KES", True),
    ("Ruth Musyoki", "KES", True),
    ("Cherd Africa Limited", "KES", True),
    ("Paris water company ltd", "KES", True),
    ("BREXEDES MORAA", "KES", True),
    ("Blair Bantu", "KES", True),
    ("Solpia Kenya ltd", "KES", True),
    ("Ciani Manga", "KES", True),
    ("Simon Munywa", "KES", True),
    ("Joseph Muna", "KES", True),
    ("Steve Njenga C/o Pure water africa", "KES", True),
    ("Abdulhakim Omar salim", "KES", True),
    ("Montell Mburu", "KES", True),
    ("Yusuf Daud", "KES", True),
    ("Issa Ali Ibrahim-Rumaisa residence", "KES", True),
    ("Jtech Mechanical services", "KES", True),
    ("Maisha Marefu Onlus", "KES", True),
    ("Central water co. Ltd", "KES", True),
    ("SYCHAR WATER C/O VITALIS", "KES", True),
    ("ZACHARY GITAU MWAURA", "KES", True),
    ("Kevin Njuguna", "KES", True),
    ("Fred Okenagwa", "KES", True),
    ("Wanjohi Ndagu", "KES", True),
    ("Sukari Industries ltd", "KES", True),
    ("Novotel westlands Nairobi", "KES", True),
    ("Juja Preparatory school", "KES", True),
    ("Issa Ali Ibrahim", "KES", True),
    ("Montell Muturi Mburu", "KES", True),
    ("Yussuf Daudi", "KES", True),
    ("Mayur Suchak", "KES", True),
    ("FRANCIS MIANO", "KES", True),
    ("Brian", "KES", True),
    ("Mburu Family Trust", "KES", True),
    ("Onur Erdem", "KES", True),
    ("Hydroconnect solution", "KES", True),
    ("Millennium Gardens- Lavington", "KES", True),
    ("Hilda makini", "KES", True),
    ("Ubora drops", "KES", True),
    ("PIDILITE EAST AFRICA LTD", "KES", True),
    ("Saints Tech Solutions", "KES", True),
    ("Zantelle Limited", "KES", True),
    ("Wotech Kenya LTD", "KES", True),
    ("Victoria Mwende", "KES", True),
    ("Mzolex consolting &Technical Services Ltd", "KES", True),
    ("Teleford Aviation", "KES", True),
    ("UTUBORA FARM", "KES", True),
    ("James Maina", "KES", True),
    ("ROBBIN KIILU", "KES", True),
    ("Kerugoya Medical centre", "KES", True),
    ("Miano njoka", "KES", True),
    ("TG Kawa Ltd", "KES", True),
    ("Naftaly", "KES", True),
    ("Abel Motanya", "KES", True),
    ("Daniel Odhiambo Nyaji", "KES", True),
    ("TRV DEVELOPERS LTD", "KES", True),
    ("TRV TOWERS LTD", "KES", True),
    ("Dennis ngugi", "KES", True),
    ("Jerry Mwangi", "KES", True),
    ("Monica", "KES", True),
    ("Bismal Investment ltd", "KES", True),
    ("Tsavo-Riruta", "KES", True),
    ("Mara Napa", "KES", True),
    ("Collins Baswony", "KES", True),
    ("Filmwala company lts", "KES", True),
    ("Hydrax water kenya ltd", "KES", True),
    ("James Kinuthia", "KES", True),
    ("Penta Geoconsultant ltd", "KES", True),
    ("Joshua Gogo", "KES", True),
    ("Urban Jua ltd", "KES", True),
    ("Florence Muaba", "KES", True),
    ("Roba Engineering ltd", "KES", True),
    ("Grobsol Technical solutions Ltd", "KES", True),
    ("Perfect Blue Springs Ltd", "KES", True),
    ("Kipeto Energy PLC", "KES", True),
    ("Hillside View water company ltd", "KES", True),
    ("Novel Green stores", "KES", True),
    ("Jake Investment", "KES", True),
    ("Barnabas Esilesi", "KES", True),
    ("Sanjos technical Services", "KES", True),
    ("Welstar International Borehole solutions", "KES", True),
    ("Kibui Peter", "KES", True),
    ("Zachary Mureithi", "KES", True),
    ("VisionPLus Automation", "KES", True),
    ("Ratech technical services", "KES", True),
    ("Heritech Ventures", "KES", True),
    ("Gilbert Onyango", "KES", True),
    ("John Chege", "KES", True),
    ("Nathan Mutai", "KES", True),
    ("Eunice Waiyaki", "KES", True),
    ("Martin", "KES", False),
    ("Flowtech E.A suppliers Ltd", "KES", True),
    ("RnH Aquatic Afridrillers", "KES", True),
    ("Algi water and Engineering systems", "KES", True),
    ("Daughters of heart of mary", "KES", True),
    ("Deylin springs ltd", "KES", True),
    ("Fitt Hydro- sytems", "KES", True),
]


def seed_customers(db: Session) -> int:
    """Insert customers that don't already exist. Returns count of new rows."""
    existing_names = {
        name for (name,) in db.query(Customer.name).all()
    }

    added = 0
    for name, currency, is_active in _CUSTOMERS:
        if name in existing_names:
            continue
        db.add(Customer(name=name, currency=currency, is_active=is_active))
        existing_names.add(name)
        added += 1

    if added:
        db.commit()
    return added
